server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cards
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    show-sql: true
  application:
    name: cards
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"



