services:
  accounts:
    image: mithunmoni/banking-accounts:0.0.1
    container_name: banking-accounts
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  loans:
    image: mithunmoni/banking-loans:0.0.1
    container_name: banking-loans
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  cards:
    image: mithunmoni/banking-cards:0.0.1
    container_name: banking-cards
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
networks:
  banking:
    driver: "bridge"
