server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    show-sql: true
  application:
    name: loans
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
