services:
  configserver:
    image: mithunmoni/banking-configserver:0.0.4
    container_name: banking-configserver
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: mithunmoni/banking-eurekaserver:0.0.4
    container_name: banking-eurekaserver
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8070:8070"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: mithunmoni/banking-accounts:0.0.4
    container_name: banking-accounts
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    ports:
      - 8080:8080
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: mithunmoni/banking-loans:0.0.4
    container_name: banking-loans
    environment:
      SPRING_APPLICATION_NAME: "loans"
    ports:
      - 8090:8090
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans-1:
    image: mithunmoni/banking-loans:0.0.4
    container_name: banking-loans-1
    environment:
      SPRING_APPLICATION_NAME: "loans"
    ports:
      - 8091:8090
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: mithunmoni/banking-cards:0.0.4
    container_name: banking-cards
    environment:
      SPRING_APPLICATION_NAME: "cards"
    ports:
      - 9000:9000
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  banking:
    driver: "bridge"
