services:
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: mithunmoni/banking-configserver:0.0.6
    container_name: banking-configserver
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: mithunmoni/banking-eurekaserver:0.0.6
    container_name: banking-eurekaserver
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8070:8070"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: mithunmoni/banking-accounts:0.0.6
    container_name: banking-accounts
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: mithunmoni/banking-loans:0.0.6
    container_name: banking-loans
    environment:
      SPRING_APPLICATION_NAME: "loans"
    ports:
      - 8090:8090
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: mithunmoni/banking-cards:0.0.6
    container_name: banking-cards
    environment:
      SPRING_APPLICATION_NAME: "cards"
    ports:
      - 9000:9000
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  gateway:
    image: mithunmoni/banking-gateway:0.0.6
    container_name: banking-gateway
    environment:
      SPRING_APPLICATION_NAME: "gateway"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    ports:
      - 8072:8072
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  banking:
    driver: "bridge"
