apiVersion: 1

deleteDatasource:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
  - name: Loki
    type: loki
    access: proxy
    url: http://gateway-grafana:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - datasourceUid: tempo
          matherRegex: "\\[.+,(.+),.+\\]"
          name: TraceId
          url: '$${__value.raw}'
    secureJsonData:
      httpHeaderValue1: "tenant1"
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET